/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendingIndexRouteImport } from './routes/trending/index'
import { Route as TendancesIndexRouteImport } from './routes/tendances/index'
import { Route as PaysIndexRouteImport } from './routes/pays/index'
import { Route as MethodologieIndexRouteImport } from './routes/methodologie/index'
import { Route as AiGeoIndexRouteImport } from './routes/ai-geo/index'
import { Route as PaysCodeRouteImport } from './routes/pays/$code'
import { Route as LegalMentionsLegalesRouteImport } from './routes/legal/mentions-legales'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal/confidentialite'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingIndexRoute = TrendingIndexRouteImport.update({
  id: '/trending/',
  path: '/trending/',
  getParentRoute: () => rootRouteImport,
} as any)
const TendancesIndexRoute = TendancesIndexRouteImport.update({
  id: '/tendances/',
  path: '/tendances/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaysIndexRoute = PaysIndexRouteImport.update({
  id: '/pays/',
  path: '/pays/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieIndexRoute = MethodologieIndexRouteImport.update({
  id: '/methodologie/',
  path: '/methodologie/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGeoIndexRoute = AiGeoIndexRouteImport.update({
  id: '/ai-geo/',
  path: '/ai-geo/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaysCodeRoute = PaysCodeRouteImport.update({
  id: '/pays/$code',
  path: '/pays/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsLegalesRoute = LegalMentionsLegalesRouteImport.update({
  id: '/legal/mentions-legales',
  path: '/legal/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/pays/$code': typeof PaysCodeRoute
  '/ai-geo/': typeof AiGeoIndexRoute
  '/methodologie/': typeof MethodologieIndexRoute
  '/pays/': typeof PaysIndexRoute
  '/tendances/': typeof TendancesIndexRoute
  '/trending/': typeof TrendingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/pays/$code': typeof PaysCodeRoute
  '/ai-geo': typeof AiGeoIndexRoute
  '/methodologie': typeof MethodologieIndexRoute
  '/pays': typeof PaysIndexRoute
  '/tendances': typeof TendancesIndexRoute
  '/trending': typeof TrendingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/pays/$code': typeof PaysCodeRoute
  '/ai-geo/': typeof AiGeoIndexRoute
  '/methodologie/': typeof MethodologieIndexRoute
  '/pays/': typeof PaysIndexRoute
  '/tendances/': typeof TendancesIndexRoute
  '/trending/': typeof TrendingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/pays/$code'
    | '/ai-geo/'
    | '/methodologie/'
    | '/pays/'
    | '/tendances/'
    | '/trending/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/pays/$code'
    | '/ai-geo'
    | '/methodologie'
    | '/pays'
    | '/tendances'
    | '/trending'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/pays/$code'
    | '/ai-geo/'
    | '/methodologie/'
    | '/pays/'
    | '/tendances/'
    | '/trending/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsLegalesRoute: typeof LegalMentionsLegalesRoute
  PaysCodeRoute: typeof PaysCodeRoute
  AiGeoIndexRoute: typeof AiGeoIndexRoute
  MethodologieIndexRoute: typeof MethodologieIndexRoute
  PaysIndexRoute: typeof PaysIndexRoute
  TendancesIndexRoute: typeof TendancesIndexRoute
  TrendingIndexRoute: typeof TrendingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending/': {
      id: '/trending/'
      path: '/trending'
      fullPath: '/trending/'
      preLoaderRoute: typeof TrendingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendances/': {
      id: '/tendances/'
      path: '/tendances'
      fullPath: '/tendances/'
      preLoaderRoute: typeof TendancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pays/': {
      id: '/pays/'
      path: '/pays'
      fullPath: '/pays/'
      preLoaderRoute: typeof PaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie/': {
      id: '/methodologie/'
      path: '/methodologie'
      fullPath: '/methodologie/'
      preLoaderRoute: typeof MethodologieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-geo/': {
      id: '/ai-geo/'
      path: '/ai-geo'
      fullPath: '/ai-geo/'
      preLoaderRoute: typeof AiGeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pays/$code': {
      id: '/pays/$code'
      path: '/pays/$code'
      fullPath: '/pays/$code'
      preLoaderRoute: typeof PaysCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions-legales': {
      id: '/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof LegalMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsLegalesRoute: LegalMentionsLegalesRoute,
  PaysCodeRoute: PaysCodeRoute,
  AiGeoIndexRoute: AiGeoIndexRoute,
  MethodologieIndexRoute: MethodologieIndexRoute,
  PaysIndexRoute: PaysIndexRoute,
  TendancesIndexRoute: TendancesIndexRoute,
  TrendingIndexRoute: TrendingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
